### ISSUE TITLE
Meet our team -- Howard 

### ISSUE THREAD

**Issue by sarahlydic** [castl350/CASTL-COR#10]
Howard Crumpton needs to be added to added to the list of contributors. 
Current professional information about him (including photo) is available here -- http://childrensnational.org/choose-childrens/find-a-provider/howard-crumpton

**Comment by mattsema** [comment]
need title and email for Howard other fields are set

**Comment by sarahlydic** [comment]
I believe Howard would be more accurately listed under "Contributors" rather than "Implementation and Development"? 

His title is Psychologist, Children's National Health System

I would not include his email address, as it is not listed on his professional site.

**Comment by mattsema** [comment]
updated
