### ISSUE TITLE
Footer elements - centering on page?

### ISSUE THREAD

**Issue by sarahlydic** [castl350/CASTL-COR#11]
Text and logo are centering to different points when re-sizing the window. Is this fixable?
![screen shot 2016-02-17 at 2 32 03 pm](https://cloud.githubusercontent.com/assets/17276503/13122127/80b837d6-d583-11e5-9486-b2803e2f96ef.png)

**Comment by mattsema** [comment]
text and logo are now within same div and centering using same css
