### ISSUE TITLE
tutorial page

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#13]
This continue button the tutorial page allowed me to skip the tutorial and head right into the modules without taking it.
![screen shot 2016-02-17 at 2 51 38 pm](https://cloud.githubusercontent.com/assets/2520615/13122323/666b6870-d584-11e5-9cf6-e97148db22a7.png)

**Comment by mattsema** [comment]
tutorial now loads within same interface as activities.  Modules are restricted until the tutorial is completed
