### ISSUE TITLE
Finished tutorial

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#14]
Learners do not need a certificate indicating that they finished the tutorial. It needs to notify then as you're doing and let them know they can continue to the modules page instead. The CLOSE and link to somewhere are conflicting…probably send learners to the learning modules landing page. Font feels different and off here.
![screen shot 2016-02-17 at 2 54 32 pm](https://cloud.githubusercontent.com/assets/2520615/13122443/e2fdd904-d584-11e5-8d55-c7fce41de738.png)

**Comment by mattsema** [comment]
certificate no longer fires when completing the tutorial
