### ISSUE TITLE
button title

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#16]
This button title felt a little off for the tutorial since it's not really an activity. any way to make this Start the tutorial.
![screen shot 2016-02-17 at 2 52 28 pm](https://cloud.githubusercontent.com/assets/2520615/13122485/179b9dfe-d585-11e5-9c4c-5851d42ec72b.png)

**Comment by mattsema** [comment]
Button reads, "Start this Tutorial"
