### ISSUE TITLE
Start did not change

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#18]
AFter i click on start module, then started activity 1, and then stopped halfway through, the START module 1 button has not changed. Starting to Continue should change when the learners has started the first lesson, not upon completing. needs to be addressed.
![screen shot 2016-02-17 at 2 59 17 pm](https://cloud.githubusercontent.com/assets/2520615/13122565/8b90c23e-d585-11e5-823e-0bcc2760d24a.png)

**Comment by mattsema** [comment]
same as #21
