### ISSUE TITLE
title

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#19]
bob's name and title is never referenced in this video introduction. kind of a important since Ann is titled and it's important for learners to buy into this and know he is a leading voice in this field. not sure if we can change now.
![screen shot 2016-02-17 at 2 58 18 pm](https://cloud.githubusercontent.com/assets/2520615/13122638/ff64ae82-d585-11e5-9ea9-f0e165e5992a.png)

**Comment by mattsema** [comment]
will update Friday 2/26

**Comment by mattsema** [comment]
in package fix - will do at later time
