### ISSUE TITLE
Module Start not shifting to continue

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#20]
After finished activity 1 and watching the video in its entirety, the module progress button still did not shift to continue or in progress…

![screen shot 2016-02-17 at 2 59 17 pm](https://cloud.githubusercontent.com/assets/2520615/13122778/b2bce7ba-d586-11e5-90cb-fb80ddca4445.png)

**Comment by mattsema** [comment]
same as #21
