### ISSUE TITLE
activity tracking not working..

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#21]
After watching activity 1 in its entirety, the activity did not get checked off….
![screen shot 2016-02-17 at 3 08 54 pm](https://cloud.githubusercontent.com/assets/2520615/13122797/ced1f828-d586-11e5-84d6-3aa1386bf312.png)

**Comment by sarahlydic** [comment]
hi kathy, just wondering what browser you were using? i used firefox and this -- as well as the other activities in M1 got checked off for me...

**Comment by mattsema** [comment]
addressed by making sure user_id gets set when user signs up not just logs in
