### ISSUE TITLE
activity tracking - activity 2

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#23]
After completing and watching all of activity 2, it did not check off as complete on my browser.

![screen shot 2016-02-17 at 3 18 30 pm](https://cloud.githubusercontent.com/assets/2520615/13123044/29013c36-d588-11e5-80d0-3c2784b9ea19.png)
![screen shot 2016-02-17 at 3 18 39 pm](https://cloud.githubusercontent.com/assets/2520615/13123047/2afa50fe-d588-11e5-9c41-a4e9f2933f8b.png)

**Comment by mattsema** [comment]
same as #21
