### ISSUE TITLE
terms of use

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#24]
Please take terms of use out of the sub nag and include a link to terms of use and privacy policy in the footer with the following language.

Review the COR website terms of use and privacy policy.
![screen shot 2016-02-17 at 3 20 07 pm](https://cloud.githubusercontent.com/assets/2520615/13123096/7d03c6b4-d588-11e5-9718-90e5f2361519.png)
![screen shot 2016-02-17 at 3 20 36 pm](https://cloud.githubusercontent.com/assets/2520615/13123098/7ee4357c-d588-11e5-9c9c-e83e2d417d23.png)

**Comment by mattsema** [comment]
added to footer, removed from nav
