### ISSUE TITLE
Update information

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#26]
In the update information area here, i complete both pulldowns during sign-up, but here my choices are not reflected. I also cannot put my cursor in a text box here behind or in the middle of the text if i wanted to make a correct to my name. 
![screen shot 2016-02-17 at 3 22 34 pm](https://cloud.githubusercontent.com/assets/2520615/13123167/f7def3e0-d588-11e5-8c9e-320c4b84d70e.png)
![screen shot 2016-02-17 at 3 22 53 pm](https://cloud.githubusercontent.com/assets/2520615/13123172/faf329f2-d588-11e5-892b-10d9204f3953.png)

**Comment by mattsema** [comment]
organization/title fields not named properly so would not show on load
