### ISSUE TITLE
email upate

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#27]
I was able to update my account to a new email (kn3t@virginia.edu) and then back to my old email? without any check as to whether that's my original account? this could be problematic for security purposes…i would recommend potentially not giving option to update email unless stronger checks are imp lace….When i tried to update my email name to semanik@virginia.edu, the page submitted and simply shot me to the resources page... no notification that that email is already taken and not mine to begin with? or that my account was not changed...
![screen shot 2016-02-17 at 3 26 12 pm](https://cloud.githubusercontent.com/assets/2520615/13123244/5554c86a-d589-11e5-92c7-196404a03699.png)

**Comment by mattsema** [comment]
increased validation checks on email field
