### ISSUE TITLE
Password retrieval process

### ISSUE THREAD

**Issue by sarahlydic** [castl350/CASTL-COR#28]
Purposefully tried the forgot password option. After submitting my email address, I was notified that a new password was sent to my email address. The enter my email address field and retrieve password button still appeared, which is confusing. Can these go away & just have the alert message appear?

![screen shot 2016-02-17 at 3 09 50 pm](https://cloud.githubusercontent.com/assets/17276503/13123269/6c53bc60-d589-11e5-8a74-09843b2c9faa.png)

**Comment by mattsema** [comment]
input fields removed after submission
