### ISSUE TITLE
old email still appears

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#29]
After changing my email to kn3t@virginia.edu from kneesen22@yahoo.com, getting a successful confirmation that the change was made, then going back to the edit profile again, the kneesen22@yahoo.com was still present, even though i received notification that it was updated successfully to kn3t@virginia.edu.
![screen shot 2016-02-17 at 3 30 01 pm](https://cloud.githubusercontent.com/assets/2520615/13123344/b416c5e2-d589-11e5-8115-a26691c0d6f2.png)

**Comment by mattsema** [comment]
related to uid not being set on signup - corrected
