### ISSUE TITLE
password update

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#31]
I was able to update my password successfully according to the site but i entered bingo22 in space 1 and bingo23 in space two. So, the password should have been checked and caught to make sure they are the same?
![screen shot 2016-02-17 at 3 59 27 pm](https://cloud.githubusercontent.com/assets/2520615/13124168/e6898394-d58d-11e5-9173-ab70f28134e8.png)

**Comment by kneesen22** [comment]
by space 1 in mean "new password", by space 2 i mean re-type new password.

**Comment by mattsema** [comment]
validation corrected on change password procedure
