### ISSUE TITLE
password update

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#32]
when trying to update my password, i was able to enter a different pw than then one i had just entered and updated to..so when i entered bingo22 as my new password, it let me update the password to bingo 11…not a problem. However, when i then went to update the pw again i was able to enter bingo 5 in the current pw field instead of bingo 11, and it let me successfully update the pw again. 
![screen shot 2016-02-17 at 4 01 01 pm](https://cloud.githubusercontent.com/assets/2520615/13124239/40cd0dda-d58e-11e5-9c32-adf51d9363ea.png)

**Comment by kneesen22** [comment]
At this point, i have no idea what my actual pw might be...

**Comment by mattsema** [comment]
validation corrected on change password procedure
