### ISSUE TITLE
fields show up again

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#33]
This message was good after i submitted my email to get my password, But, in addition to the notification i see the fields again, which shouldn't be happening. confusing for learners...
![screen shot 2016-02-17 at 4 04 10 pm](https://cloud.githubusercontent.com/assets/2520615/13124358/8e28aaee-d58e-11e5-84ab-3d9aed626738.png)

**Comment by mattsema** [comment]
removed fields on submit
