### ISSUE TITLE
Grammar fixes

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#4]
Please change number 5 to Five . Change student-teacher to teacher-student.
Add periods to all bulleted statements since the bolded lead in makes each a complete sentence.

Change to:
Five online learning modules that can be taken independently or as part of a group learning experience.

Certification for each module you complete.

![grammar issues](https://cloud.githubusercontent.com/assets/2520615/13121264/a4763f8c-d57f-11e5-95af-ece6290de96d.png)

**Comment by stevelessi** [comment]
Fixed

**Comment by sarahlydic** [comment]
Now that the word "five" is capitalized, the word "online" needs to be all lower-case. :)

**Comment by stevelessi** [comment]
Fixed
