### ISSUE TITLE
How to Use COR - text styling

### ISSUE THREAD

**Issue by sarahlydic** [castl350/CASTL-COR#46]
I'm not crazy about how the text at the top of the page is styled with white boxes around each paragraph. Could these boxes be united? 
![screen shot 2016-02-26 at 10 41 16 am](https://cloud.githubusercontent.com/assets/17276503/13356897/ba45d848-dc75-11e5-9b15-f2fecbe8d2f5.png)

**Comment by mattsema** [comment]
information doesn't mix into one box well - can look again
