### ISSUE TITLE
Tutorial - Module overview page responsiveness

### ISSUE THREAD

**Issue by sarahlydic** [castl350/CASTL-COR#49]
Once the page gets to a certain width, the message on the Tutorial overlaps with the START button
![screen shot 2016-02-26 at 11 39 58 am](https://cloud.githubusercontent.com/assets/17276503/13358532/bef6eca8-dc7d-11e5-9de3-e249e54aa457.png)

**Comment by mattsema** [comment]
moved message out and addressed bootstrap classes controlling the sizing of the panels
