### ISSUE TITLE
Activity page responsiveness

### ISSUE THREAD

**Issue by sarahlydic** [castl350/CASTL-COR#50]
Titles aren't centering within boxes. Also, the boxes can become more narrow than the START/IN PROGRESS/COMPLETE buttons.
![screen shot 2016-02-26 at 12 17 14 pm](https://cloud.githubusercontent.com/assets/17276503/13359595/1d3ea56c-dc83-11e5-8c9f-d48183e92303.png)

**Comment by mattsema** [comment]
sizing result of non-standard screen size with bootstrap classes can't fix
