### ISSUE TITLE
Finished module button

### ISSUE THREAD

**Issue by sarahlydic** [castl350/CASTL-COR#51]
this is a previous issue -- 
button styling feels different from rest of site
closed and link buttons seem conflicting
![screen shot 2016-02-26 at 12 20 41 pm](https://cloud.githubusercontent.com/assets/17276503/13359888/5c507edc-dc84-11e5-80e2-7efd7d04b0cc.png)

**Comment by sarahlydic** [comment]
I like the new styling. The closed and link buttons still seem conflicting.

**Comment by mattsema** [comment]
addressed in other issue
