### ISSUE TITLE
message location

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#56]
This message "please complete" needs to live elsewhere...probably at the top of this page spanning across the whole things..and perhaps in a light orange background since the whole site is blue and this blends too much....

Also instead of Module 0...just hide that..don't display if the module is 0. The Before You Start: Tutorial is perfect.
![screen shot 2016-03-01 at 10 39 01 am](https://cloud.githubusercontent.com/assets/2520615/13466963/43e047e4-e06a-11e5-8772-51c065d673a2.png)

**Comment by sarahlydic** [comment]
I like the message with the orange spanning the page. The font is different (serif) from other fonts & it seems to be floating near the top of the bar. More like alert on CASTL coaching?

**Comment by mattsema** [comment]
added to top of module home page
