### ISSUE TITLE
Styling issue

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#57]
The styling of this page is different than the rest. It looks like the title should be in the grey, and the white provides background for the content on other page....
![screen shot 2016-03-01 at 10 34 11 am](https://cloud.githubusercontent.com/assets/2520615/13466987/576f9d50-e06a-11e5-8d60-90749667f079.png)

**Comment by kneesen22** [comment]
this page seems more consistent with all the others? i would go with this as the example for the research page
![screen shot 2016-03-01 at 10 34 17 am](https://cloud.githubusercontent.com/assets/2520615/13467044/8a0c8714-e06a-11e5-9a12-025b189d0a77.png)

**Comment by mattsema** [comment]
left titles in grey so that content was in white box
