### ISSUE TITLE
hard to read...

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#58]
![screen shot 2016-03-01 at 10 40 28 am](https://cloud.githubusercontent.com/assets/2520615/13467100/b322fcdc-e06a-11e5-9228-fca0515a6f54.png)

Matt, not for you to fix but the instructions here were really hard to read..on my laptop it felt like the wording was often tiny in the packages, wonder if there is a way to scale them up slightly...again, not urgent but something to talk about at our next meeting.

**Comment by mattsema** [comment]
increased package embed size
