### ISSUE TITLE
Tutorial icon image

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#59]
love the choice for this tutorial icon image, but it's slightly off on the height...little longer than the others...seems like a quick fix and will strengthen the look and feel?
![screen shot 2016-03-01 at 10 40 01 am](https://cloud.githubusercontent.com/assets/2520615/13467163/f1dae6a6-e06a-11e5-8491-a32a370b21c6.png)

**Comment by mattsema** [comment]
adjusted icon height to match other modules
