### ISSUE TITLE
activity issue

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#60]
This is the activity where i entered information into the fields but it didn't really go anywhere when i submitted..ended up using the arrows to maneuver forward with out any feedback or knowledge of what to do with answers...
![screen shot 2016-03-01 at 10 57 47 am](https://cloud.githubusercontent.com/assets/2520615/13467202/26bb4f3c-e06b-11e5-8113-e5ff298b7967.png)

**Comment by kneesen22** [comment]
Matt, not for you to fix but just adding it in so it is on the radar as we start to test the packages themselves more closely.

**Comment by mattsema** [comment]
see #78
