### ISSUE TITLE
Notice of completion on the module page

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#61]
On this module page, there should also be a notice of completion (a brief one) just as there is one on the more general page that shows all of the modules. If i come to this page first for any reason, it doesn't provide any information to me about the completion status...so just a short notice somewhere in the white space or spanning in a div below this white box....maybe play around with it?
![screen shot 2016-03-01 at 10 58 57 am](https://cloud.githubusercontent.com/assets/2520615/13467269/7c2c88b4-e06b-11e5-8bc6-aba9a95377a1.png)

**Comment by mattsema** [comment]
added notice
