### ISSUE TITLE
package disappeared

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#62]
This package kinda disappeared randomly after being done and clicking around...might be a fluke but just putting it in to note..did not have this issue with others...let's leave it to test further when we hit the packages more intensely?

![screen shot 2016-03-01 at 10 58 47 am](https://cloud.githubusercontent.com/assets/2520615/13467303/a6d1e528-e06b-11e5-8dcd-9a35a476aa38.png)

**Comment by mattsema** [comment]
adapted javascript that was hiding activities when modals were active
