### ISSUE TITLE
example of weird tracking

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#63]
this is the example i noted of a random activity that i may not have gone through all the slides, but watched as a whole etc...and it kept the completion status from changing..that can be fixed if we make the completion tracking a little more robust by having multiple ways to complete...again, not something to fix but something to hold on to...
![screen shot 2016-03-01 at 10 58 31 am](https://cloud.githubusercontent.com/assets/2520615/13467338/d31f1f4c-e06b-11e5-8a02-d41a065672dc.png)

**Comment by mattsema** [comment]
not addressing tracking at this time
