### ISSUE TITLE
M2 A3 Sorting Navigation

### ISSUE THREAD

**Issue by sarahlydic** [castl350/CASTL-COR#66]
The navigation for this activity is frustrating. The submit button is very small, and upon returning to the sorting page, the buttons change to PREV & NEXT instead of SUBMIT...
![screen shot 2016-03-09 at 3 19 19 pm](https://cloud.githubusercontent.com/assets/17276503/13649172/5d1c2732-e60a-11e5-8d2d-846fec8adeee.png)

**Comment by mattsema** [comment]
see #72
