### ISSUE TITLE
M2 A1 Navigation

### ISSUE THREAD

**Issue by sarahlydic** [castl350/CASTL-COR#67]
When we switched from forced linear navigation to letting the learner navigate, this introduced complicated navigation into this activity with a "Return to Menu" button... Thoughts for how to do this more simply?
![screen shot 2016-03-09 at 3 20 37 pm](https://cloud.githubusercontent.com/assets/17276503/13649248/c188b15e-e60a-11e5-99fd-fab4130d61e9.png)

**Comment by sarahlydic** [comment]
A similar navigation issue appears in M2 A2 with the two mindfulness practices.

**Comment by mattsema** [comment]
see #72
