### ISSUE TITLE
M3 A2 text small (not just w/ this activity)

### ISSUE THREAD

**Issue by sarahlydic** [castl350/CASTL-COR#70]
a note that text is frustratingly small at times, not just with this activity. wish packages could display at a larger size.
<img width="619" alt="screen shot 2016-03-09 at 4 10 26 pm" src="https://cloud.githubusercontent.com/assets/17276503/13650792/5e2fe264-e612-11e5-80ca-c3d763f974d9.png">

**Comment by sarahlydic** [comment]
![screen shot 2016-03-09 at 4 22 03 pm](https://cloud.githubusercontent.com/assets/17276503/13650945/11d09e30-e613-11e5-8c36-0901b63370fb.png)

**Comment by sarahlydic** [comment]
![screen shot 2016-03-09 at 4 27 05 pm](https://cloud.githubusercontent.com/assets/17276503/13651096/c719da2c-e613-11e5-9f92-ecdb6bf6619b.png)

**Comment by mattsema** [comment]
see #72
