### ISSUE TITLE
Need buffering

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#74]
Matt, i like this message and where it is! please add buffering/padding on the top so it's not stuck to the top border...then it will be all set.

![screen shot 2016-03-10 at 12 32 50 pm](https://cloud.githubusercontent.com/assets/2520615/13678676/f0337af8-e6bd-11e5-851a-3ea0029a46f5.png)

**Comment by mattsema** [comment]
addressed padding and other styling to match complete message
