### ISSUE TITLE
certificate notice

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#76]
This message feels weird and i can't imagine wanting to go from here to print out a certificate...

let's talk about getting rid of this notification and simply having learners use the navigation to proceed back to the module page where there is a similar message box as in CASTL VC that says "yay! you have completed this module. you can print out your certificate or something..."
![screen shot 2016-03-10 at 12 44 35 pm](https://cloud.githubusercontent.com/assets/2520615/13678737/39abb1dc-e6be-11e5-88fc-81c1382de32e.png)

**Comment by mattsema** [comment]
see #81
