### ISSUE TITLE
module 1 activity 7

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#78]
this is the on package that has an issue within. the submit buttons here do NOT work to submit answers..i'm also wondering how you got two open-ended boxes to sit on one page, since articulate does not allow this functionality? maybe this is the problem..i can type in the box..but the submit button doesn't go anywhere...it happens on all three interactive pages in this exercise.
![screen shot 2016-03-10 at 12 44 00 pm](https://cloud.githubusercontent.com/assets/2520615/13678816/b24b6880-e6be-11e5-853a-c2b22b80adff.png)

**Comment by mattsema** [comment]
in-package correction on hold
submit requires use of the space bar
while multiple boxes can be on the same page only one can be used to submit to a scorm database setup
