### ISSUE TITLE
message location

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#79]
Matt, please left align this message instead of centering it...Bold "You have completed this module!"  Then image with Obtain Your Certificate behind it...let's see how that looks and keep playing on monday. its close.
![screen shot 2016-03-10 at 12 51 20 pm](https://cloud.githubusercontent.com/assets/2520615/13678912/39c1564e-e6bf-11e5-9a69-9909e6133036.png)

**Comment by mattsema** [comment]
addressed styling of message
