### ISSUE TITLE
after tutorial

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#80]
After the tutorial, there is no way for me to proceed to the learning modules other than using the navigation or breadcrumbs....on the bottom right there should be a navigation point here that should also be part of the other modules....we'll talk about this on monday?
![screen shot 2016-03-10 at 12 34 11 pm](https://cloud.githubusercontent.com/assets/2520615/13678961/6709a368-e6bf-11e5-986a-e3a778ba2c05.png)

**Comment by mattsema** [comment]
see #81
