### ISSUE TITLE
Add navigation

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#81]
Matt, right here..on the last activity of a learning module, we need the right hand side to say "Complete Module"..that link should take learners to the Modules main page for that module, or even the broad modules landing page with a CASTL VC like message...."You've completed Module X. You can obtain a certificate for this module below or continue with the next module." that will help us get rid of the notification message popping up.
![screen shot 2016-03-10 at 1 02 47 pm](https://cloud.githubusercontent.com/assets/2520615/13679246/cfeb1c3a-e6c0-11e5-898b-53f90677f2ca.png)

**Comment by kneesen22** [comment]
referring to this notification that needs to go away in general...
![screen shot 2016-03-10 at 1 03 03 pm](https://cloud.githubusercontent.com/assets/2520615/13679269/e459bff0-e6c0-11e5-8f75-508fd92f2710.png)

**Comment by mattsema** [comment]
Added return buttons to activity page and changed completion message to return to modules home when complete
