### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by fromthepass** [castl350/CASTL-COR#82]
This is not an issue with the COR website, but under All About COR > Meet Our Team, the link "More About Steven" (re: Steven Lessick) takes you to an error 404 webpage (e.g. page not found). 

COR Webpage
http://dev.corclassrooms.org/about/team.php

Webpage result from clicking on "More About Steven"
http://curry.virginia.edu/about/directory/steven-p.-lessick

**Comment by mattsema** [comment]
removed link
