### ISSUE TITLE
Typo in text

### ISSUE THREAD

**Issue by fromthepass** [castl350/CASTL-COR#83]
Location: How Can I Use COR? > How to Use COR under Select Modules Based on the Needs of Your Organization http://dev.corclassrooms.org/use/how_to_use.php

Issue: In the second sentence in this section, "These modules and can be used alone or in tandem with other modules for a professional development experience tailored to your needs," the "and" after "modules" seems to be a type. I believe that it should read "These modules can be used alone or in tandem..."

**Comment by mattsema** [comment]
removed "and"
