### ISSUE TITLE
Potentially broken hyperlink

### ISSUE THREAD

**Issue by fromthepass** [castl350/CASTL-COR#84]
Location: Help > Frequently Asked Questions > I want to make sure that I’m using the COR learning modules in an appropriate way with my students or staff? Is there someone I can talk with further?
(http://dev.corclassrooms.org/help/index.php)

Issue: The hyperlink "contact us" included near the end of the sentence (e.g. "please **contact us** to request more information") does not open to anything when I click on it. If ctrl + click the hyperlink, a blank tab opens in my web browser with "mailto:help@corclassrooms.org" included in the address bar. The same text also appears in the bottom left hand corner of the webpage if I simply hover over the hyperlink.

**Comment by mattsema** [comment]
The link is designed to open the browser's default mail application.  If no application is set up, the link will not do anything
