### ISSUE TITLE
Resources & Citations

### ISSUE THREAD

**Issue by fromthepass** [castl350/CASTL-COR#85]
Location(s): Learning Modules > all modules (1-5)

Issue: I am not sure this is an issue, but to the left of each of the module sections is an area that has two sections: "Objectives" and "Resources& Citations." Though supplemental citations exist for most modules, this section contains no information for any particular video. If we want to align supplemental resources with ideas discussed within specific module videos, we may want to utilize this section so that as people view videos, they can immediately follow-up with the supplemental materials they are particularly interested in.

**Comment by mattsema** [comment]
fixed
