### ISSUE TITLE
Contact Info Submitted - No confirmation page

### ISSUE THREAD

**Issue by kneesen22** [castl350/CASTL-COR#9]
Submitted a request to the contact form…after submitting when to blank page with on confirmation for user.
![submitted contact form lands on blank page](https://cloud.githubusercontent.com/assets/2520615/13121360/0fc2e362-d580-11e5-9f87-4d388e8d3067.png)

**Comment by stevelessi** [comment]
Updated to return to email page.  Will need to create js function to return feedback

**Comment by kneesen22** [comment]
Also, note that the URL sends users to an admin area so to speak..that's not ok….users should not know that there is an admin section

**Comment by castl350** [comment]
Message is displayed instead of fields when email is sent
admin section will no longer be accessible by general user
